"""Deterministic AppealOS domain: fixtures, hashing, consent, mandate, state.

Gemini output never mutates these objects.  All transitions and external-write
guards live here so the model cannot authorize actions or write case state.
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import uuid
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional

RIDER_ACCOUNT_ID = "rider-r-2048"
PLATFORM = "mockdrop"
ALLEGATION_TYPE = "ABNORMAL_LOCATION"
SUPPLEMENT_TEMPLATE = "DEVICE_NETWORK_HANDOFF_V1"
REQUIRED_DEVICE_LOG_FIELDS = [
    "occurredAt",
    "networkFrom",
    "networkTo",
    "reason",
]

# This hash must match apps/mockdrop/src/fixtures.js.  It is verified at import
# time by canonicalization tests rather than being generated by a model.
DEVICE_LOG_FIXTURE = {
    "deviceId": "mock-device-r-2048",
    "occurredAt": "2026-08-18T02:17:00.000Z",
    "networkFrom": "5G",
    "networkTo": "LTE",
    "reason": "CELLULAR_HANDOFF",
}
DEVICE_LOG_SHA256 = "a59508ce61967f6a170afa6b5d0794474510925508e5be449af3926b67f3ff79"

# Synthetic notice deadline is deterministic.  Gemini may suggest a value, but
# the authoritative deadline is computed from this fixture by code.
SYNTHETIC_NOTICE = """MockDrop Account Notice

Account: rider-r-2048
Status: SUSPENDED
Reason: ABNORMAL_LOCATION
Deadline: 2026-09-03T23:59:59Z

A cellular-network handoff was mistaken for location fraud."""

DETERMINISTIC_DEADLINE = "2026-09-03T23:59:59Z"

EVIDENCE_ARTIFACTS = {
    "delivery-receipt": {
        "artifactId": "delivery-receipt",
        "kind": "DELIVERY_RECEIPT",
        "capturedAt": "2026-08-18T02:15:00.000Z",
        "plaintext": {
            "orderId": "mock-order-r-2048",
            "deliveredAt": "2026-08-18T02:15:00.000Z",
            "customerZone": "zone-7",
        },
    },
    "gps-trace": {
        "artifactId": "gps-trace",
        "kind": "GPS_TRACE",
        "capturedAt": "2026-08-18T02:16:30.000Z",
        "plaintext": {
            "traceId": "mock-trace-r-2048",
            "startedAt": "2026-08-18T02:10:00.000Z",
            "endedAt": "2026-08-18T02:17:00.000Z",
            "networkChanges": [
                {"at": "2026-08-18T02:17:00.000Z", "from": "5G", "to": "LTE"}
            ],
        },
    },
    "device-log": {
        "artifactId": "device-log",
        "kind": "DEVICE_LOG",
        "capturedAt": "2026-08-18T02:17:00.000Z",
        "plaintext": DEVICE_LOG_FIXTURE,
    },
}

POLICY_PROFILE = {
    "policyProfileId": "mockdrop-policy-v1",
    "clauses": {
        "POLICY-LOCATION-1": (
            "Abnormal-location suspensions are reversed when a corroborated "
            "device log shows a cellular handoff during an active delivery."
        ),
        "POLICY-EVIDENCE-1": (
            "A device log must contain occurredAt, networkFrom, networkTo, "
            "and reason and match the disclosed artifact hash."
        ),
    },
}

ALLOWED_CLAIM_TYPES = {"OBSERVED_EVENT", "CAUSAL_EXPLANATION", "POLICY_REQUEST"}
ALLOWED_PURPOSES = {"TIMELINE", "POLICY_MATCH", "DRAFT_CLAIMS"}
DEFAULT_ANALYSIS_PURPOSES = ["TIMELINE", "POLICY_MATCH", "DRAFT_CLAIMS"]

STATES = [
    "NOTICE_RECEIVED",
    "PARSED",
    "CONSENTED",
    "MANDATE_APPROVED",
    "SUBMISSION_PENDING",
    "ACKNOWLEDGED",
    "SUPPLEMENT_REQUESTED",
    "SUPPLEMENTED",
    "DECIDED_APPROVED",
    "ACCOUNT_ACTIVE",
]


def canonicalize(value: Any) -> str:
    """RFC 8785-style canonical JSON compatible with apps/mockdrop/src/canonical.js."""
    if value is None or not isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=True, separators=(",", ":"))

    if isinstance(value, list):
        return "[" + ",".join(canonicalize(item) for item in value) + "]"

    entries = sorted(
        (key, item)
        for key, item in value.items()
        if item is not None
    )
    return (
        "{"
        + ",".join(
            f"{json.dumps(key, ensure_ascii=True)}:{canonicalize(item)}"
            for key, item in entries
        )
        + "}"
    )


def sha256_canonical(value: Any) -> str:
    return hashlib.sha256(canonicalize(value).encode("utf-8")).hexdigest()


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def parse_datetime(value: str) -> _dt.datetime:
    """Parse an ISO timestamp as an aware datetime for authorization checks."""
    parsed = _dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=_dt.timezone.utc)
    return parsed


def _assert_fixture_hash() -> None:
    actual = sha256_canonical(DEVICE_LOG_FIXTURE)
    if actual != DEVICE_LOG_SHA256:
        raise RuntimeError(
            f"Device log hash mismatch: expected {DEVICE_LOG_SHA256}, got {actual}"
        )


_assert_fixture_hash()


def evidence_inventory() -> List[Dict[str, str]]:
    return [
        {
            "artifactId": item["artifactId"],
            "kind": item["kind"],
            "capturedAt": item["capturedAt"],
            "plaintextSha256": sha256_canonical(item["plaintext"]),
        }
        for item in EVIDENCE_ARTIFACTS.values()
    ]


@dataclass
class AnalysisConsent:
    consentId: str
    caseId: str
    artifactIds: List[str]
    purposes: List[str]
    allowGeminiProcessing: bool
    approvedAt: str
    expiresAt: str

    @classmethod
    def create(cls, case_id: str, artifact_ids: List[str], now: _dt.datetime) -> "AnalysisConsent":
        requested = list(dict.fromkeys(artifact_ids))
        if not requested:
            raise ValueError("At least one evidence artifact must be selected")
        if not set(requested).issubset(EVIDENCE_ARTIFACTS):
            raise ValueError("Unknown evidence artifact in consent")
        return cls(
            consentId=f"consent-{uuid.uuid4()}",
            caseId=case_id,
            artifactIds=requested,
            purposes=list(DEFAULT_ANALYSIS_PURPOSES),
            allowGeminiProcessing=True,
            approvedAt=now.isoformat(),
            expiresAt=(now + _dt.timedelta(hours=1)).isoformat(),
        )

    def is_active(self, now: Optional[_dt.datetime] = None) -> bool:
        instant = now or _dt.datetime.now(_dt.timezone.utc)
        return self.allowGeminiProcessing and instant < parse_datetime(self.expiresAt)

    def allows_artifact(self, artifact_id: str) -> bool:
        return artifact_id in self.artifactIds


@dataclass
class AppealMandate:
    mandateId: str
    caseId: str
    destinationAdapter: str
    destinationAccountId: str
    approvedClaimIds: List[str]
    allowedActions: List[str]
    approvedArtifactIds: List[str]
    allowedSupplementTemplate: str
    maxSupplementCycles: int
    supplementCyclesUsed: int
    approvedAt: str
    expiresAt: str

    def is_active(self, now: Optional[_dt.datetime] = None) -> bool:
        instant = now or _dt.datetime.now(_dt.timezone.utc)
        return instant < parse_datetime(self.expiresAt)

    def allows(
        self,
        action: str,
        *,
        destination_adapter: Optional[str] = None,
        destination_account_id: Optional[str] = None,
        now: Optional[_dt.datetime] = None,
    ) -> bool:
        if action not in self.allowedActions or not self.is_active(now):
            return False
        if destination_adapter is not None and destination_adapter != self.destinationAdapter:
            return False
        if destination_account_id is not None and destination_account_id != self.destinationAccountId:
            return False
        return True

    def allows_artifact(self, artifact_id: str) -> bool:
        return artifact_id in self.approvedArtifactIds

    def can_supplement(
        self,
        artifact_id: str,
        template: str,
        *,
        destination_adapter: Optional[str] = None,
        destination_account_id: Optional[str] = None,
        now: Optional[_dt.datetime] = None,
    ) -> bool:
        return (
            self.allows(
                "SUPPLEMENT",
                destination_adapter=destination_adapter,
                destination_account_id=destination_account_id,
                now=now,
            )
            and self.allows_artifact(artifact_id)
            and template == self.allowedSupplementTemplate
            and self.supplementCyclesUsed < self.maxSupplementCycles
        )


@dataclass
class DemoCase:
    caseId: str = field(default_factory=lambda: f"case-{uuid.uuid4()}")
    ownerId: str = "synthetic-owner"
    platform: str = PLATFORM
    accountId: str = RIDER_ACCOUNT_ID
    allegationType: str = ALLEGATION_TYPE
    state: str = "NOTICE_RECEIVED"
    deadlineAt: str = DETERMINISTIC_DEADLINE
    deadlineSourceText: str = SYNTHETIC_NOTICE
    consent: Optional[AnalysisConsent] = None
    mandate: Optional[AppealMandate] = None
    claims: List[Dict[str, Any]] = field(default_factory=list)
    appealId: Optional[str] = None
    platformReceipts: List[Dict[str, Any]] = field(default_factory=list)
    timeline: List[Dict[str, Any]] = field(default_factory=list)
    quarantinedArtifactIds: List[str] = field(default_factory=list)
    version: int = 0
    createdAt: str = field(default_factory=lambda: _dt.datetime.now(_dt.timezone.utc).isoformat())
    updatedAt: str = field(default_factory=lambda: _dt.datetime.now(_dt.timezone.utc).isoformat())

    def record(
        self,
        event_type: str,
        actor: str,
        data: Optional[Dict[str, Any]] = None,
        to_state: Optional[str] = None,
    ) -> Dict[str, Any]:
        self.version += 1
        self.updatedAt = _dt.datetime.now(_dt.timezone.utc).isoformat()
        if to_state and to_state != self.state:
            self.state = to_state
        event = {
            "eventId": f"event-{uuid.uuid4()}",
            "caseId": self.caseId,
            "caseVersion": self.version,
            "type": event_type,
            "actor": actor,
            "state": self.state,
            "createdAt": self.updatedAt,
            "data": data or {},
            "previousEventHash": (
                self.timeline[-1].get("eventHash") if self.timeline else None
            ),
        }
        event["eventHash"] = sha256_canonical(event)
        self.timeline.append(event)
        return event

    def verify_timeline(self) -> bool:
        previous_hash: Optional[str] = None
        for event in self.timeline:
            if event.get("previousEventHash") != previous_hash:
                return False
            claimed_hash = event.get("eventHash")
            if not claimed_hash:
                return False
            unsigned_event = {
                key: value for key, value in event.items() if key != "eventHash"
            }
            if sha256_canonical(unsigned_event) != claimed_hash:
                return False
            previous_hash = claimed_hash
        return True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "caseId": self.caseId,
            "ownerId": self.ownerId,
            "platform": self.platform,
            "accountId": self.accountId,
            "allegationType": self.allegationType,
            "state": self.state,
            "deadlineAt": self.deadlineAt,
            "consent": {
                "consentId": self.consent.consentId,
                "artifactIds": self.consent.artifactIds,
                "purposes": self.consent.purposes,
                "allowGeminiProcessing": self.consent.allowGeminiProcessing,
                "approvedAt": self.consent.approvedAt,
                "expiresAt": self.consent.expiresAt,
            }
            if self.consent
            else None,
            "mandate": {
                "mandateId": self.mandate.mandateId,
                "destinationAdapter": self.mandate.destinationAdapter,
                "destinationAccountId": self.mandate.destinationAccountId,
                "allowedActions": self.mandate.allowedActions,
                "approvedClaimIds": self.mandate.approvedClaimIds,
                "approvedArtifactIds": self.mandate.approvedArtifactIds,
                "supplementCyclesUsed": self.mandate.supplementCyclesUsed,
                "maxSupplementCycles": self.mandate.maxSupplementCycles,
                "expiresAt": self.mandate.expiresAt,
            }
            if self.mandate
            else None,
            "claims": self.claims,
            "appealId": self.appealId,
            "platformReceipts": self.platformReceipts,
            "version": self.version,
            "createdAt": self.createdAt,
            "updatedAt": self.updatedAt,
            "timeline": self.timeline,
            "quarantinedArtifactIds": self.quarantinedArtifactIds,
            "timelineIntegrity": {
                "verified": self.verify_timeline(),
                "headHash": self.timeline[-1].get("eventHash") if self.timeline else None,
            },
        }

    def to_persistable(self) -> Dict[str, Any]:
        """Full round-trip representation used by durable stores."""
        data = self.to_dict()
        data["consent"] = asdict(self.consent) if self.consent else None
        data["mandate"] = asdict(self.mandate) if self.mandate else None
        return data

    @classmethod
    def from_persistable(cls, data: Dict[str, Any]) -> "DemoCase":
        """Reconstruct a case from a durable-store payload."""
        consent_data = data.get("consent")
        mandate_data = data.get("mandate")
        return cls(
            caseId=data["caseId"],
            ownerId=data.get("ownerId", "synthetic-owner"),
            platform=data.get("platform", PLATFORM),
            accountId=data.get("accountId", RIDER_ACCOUNT_ID),
            allegationType=data.get("allegationType", ALLEGATION_TYPE),
            state=data.get("state", "NOTICE_RECEIVED"),
            deadlineAt=data.get("deadlineAt", DETERMINISTIC_DEADLINE),
            deadlineSourceText=data.get("deadlineSourceText", SYNTHETIC_NOTICE),
            consent=AnalysisConsent(**consent_data) if consent_data else None,
            mandate=AppealMandate(**mandate_data) if mandate_data else None,
            claims=data.get("claims") or [],
            appealId=data.get("appealId"),
            platformReceipts=data.get("platformReceipts") or [],
            timeline=data.get("timeline") or [],
            quarantinedArtifactIds=data.get("quarantinedArtifactIds") or [],
            version=data.get("version", 0),
            createdAt=data.get("createdAt", ""),
            updatedAt=data.get("updatedAt", ""),
        )
